# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0002_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='dojo_secrets.User'),
        ),
    ]
